# Generated by Django 4.2.20 on 2025-04-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='avaiable_copies',
            new_name='available_copies',
        ),
        migrations.AddField(
            model_name='book',
            name='total_copies',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
