# Generated by Django 4.2.20 on 2025-04-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_avaiable_copies_book_available_copies_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowedbook',
            name='is_returned',
        ),
        migrations.AlterField(
            model_name='borrowedbook',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
